server:
  port: 8080
spring:
  application:
    name: orderService
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
  config:
    import:
      - nacos:nacos-config-example.properties?refresh=true